<a href="https://colab.research.google.com/github/manishl7/Multiimageclassification/blob/master/Tweetclassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Unzipping the data set

In [ ]:
cd /content/drive/My Drive/RNN/

/content/drive/My Drive/RNN


In [ ]:
#datasetlink:https://www.kaggle.com/crowdflower/twitter-airline-sentiment
!unzip /content/drive/MyDrive/RNN/twitter_airline.zip

Archive:  /content/drive/MyDrive/RNN/twitter_airline.zip
  inflating: Tweets.csv              
  inflating: database.sqlite         


In [ ]:
df=pd.read_csv('Tweets.csv')
df.head()

tweet_id  ...               user_timezone
0  570306133677760513  ...  Eastern Time (US & Canada)
1  570301130888122368  ...  Pacific Time (US & Canada)
2  570301083672813571  ...  Central Time (US & Canada)
3  570301031407624196  ...  Pacific Time (US & Canada)
4  570300817074462722  ...  Pacific Time (US & Canada)

[5 rows x 15 columns]

In [ ]:
#Splitting data

from sklearn.model_selection import train_test_split
y=df['airline_sentiment']
X=df['text']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [ ]:
X_train.shape
X_test.shape

(4832,)

In [ ]:
# Placing countvectorization,tfidf,transformation and classificaition using a pipeline 
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
model=Pipeline([('tfidf',TfidfVectorizer()),('classifier',LinearSVC())])

In [ ]:
#Training our model
model.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('classifier',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
        

In [ ]:
#Printing out the metrics
from sklearn import metrics

predictions=model.predict(X_test)

print(metrics.classification_report(y_test,predictions))
print(metrics.confusion_matrix(y_test,predictions))
print(f'Our model is {metrics.accuracy_score(y_test,predictions)*100} % accurate')




              precision    recall  f1-score   support

    negative       0.85      0.91      0.88      3085
     neutral       0.63      0.56      0.59       984
    positive       0.77      0.68      0.72       763

    accuracy                           0.80      4832
   macro avg       0.75      0.71      0.73      4832
weighted avg       0.79      0.80      0.79      4832

[[2793  218   74]
 [ 355  548   81]
 [ 147  100  516]]
Our model is 79.82201986754967 % accurate


In [ ]:
#Prediction

def pred(text):
  prediction=model.predict(text)
  if prediction=='negative':
    print("The tweet is negative")
  elif prediction=='neutral':
    print('The Tweet is Neutral')
  elif prediction=='positive':
    print('The tweet is positive')


In [ ]:
pred(['Today is a good day'])
pred(['I am not feeling good'])
pred(['I am going to the church'])

The tweet is positive
The tweet is negative
The Tweet is Neutral


NameError: ignored